shamefullyHoist: true
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1

packages:
  - content
  - packages/*

overrides:
  rolldown: ^1.0.0-rc.5
  vite: 8.0.0-beta.15

patchedDependencies:
  mdast-util-to-hast: patches/mdast-util-to-hast.patch

catalogs:
  build:
    tsdown: ^0.20.3
    typescript: ^5.9.3
  css:
    sass-embedded: ^1.97.3
  database:
    mongoose: ^9.1.5
  iconify:
    "@iconify-json/fa7-solid": ^1.2.3
    "@iconify-json/ri": ^1.2.7
  lint:
    "@zinkawaii/eslint-config": ^0.4.1
    "@zinkawaii/stylelint-config": ^0.4.0
    eslint: ^9.39.2
    stylelint: ^17.0.0
  markdown:
    kerria: ^0.4.2
    mdast-util-gfm-footnote: ^2.1.0
    mdast-util-gfm-strikethrough: ^2.0.0
    mdast-util-to-string: ^4.0.0
    micromark-extension-gfm-footnote: ^2.1.0
    micromark-extension-gfm-strikethrough: ^2.1.0
    micromark-util-symbol: ^2.0.1
    remark-breaks: ^4.0.0
    remark-frontmatter: ^5.0.0
    remark-math: ^6.0.0
    remark-mdc: ^3.10.0
    remark-parse: ^11.0.0
    remark-rehype: ^11.1.2
    unified: ^11.0.5
    unist-util-visit: ^5.1.0
  nuxt:
    "@bikariya/image-viewer": ^0.0.3
    "@bikariya/modals": ^0.0.3
    "@bikariya/shiki": ^0.0.3
    "@nuxt/devtools": ^3.1.1
    "@nuxt/fonts": ^0.13.0
    "@nuxt/icon": ^2.2.1
    "@nuxt/image": ^2.0.0
    "@nuxtjs/seo": ^3.3.0
    "@pinia/nuxt": ^0.11.3
    "@vueuse/nuxt": ^14.1.0
    nuxt: ^4.3.0
  test:
    vitest: ^4.0.18
  types:
    "@types/node": ^25.3.0
    "@types/picomatch": ^4.0.2
    "@zinkawaii/tsconfig": ^0.0.2
  utils:
    "@clack/prompts": ^0.11.0
    "@shikijs/transformers": ^3.21.0
    animejs: ^4.3.5
    arktype: ^2.1.29
    bgmt: ^0.1.3
    chokidar: ^5.0.0
    consola: ^3.4.2
    crypto-es: ^3.1.2
    defu: ^6.1.4
    github-slugger: ^2.0.0
    hookable: ^6.0.1
    katex: ^0.16.27
    pathe: ^2.0.3
    picomatch: ^4.0.3
    plain-shiki: ^0.3.2
    propathy: ^0.2.1
    shiki: ^3.21.0
    svgo: ^4.0.0
    temporal-polyfill: ^0.3.0
    tinyexec: ^1.0.2
    tinyglobby: ^0.2.15
    unemail: ^0.3.0
    unrun: ^0.2.26
    uqr: ^0.1.2
    yaml: ^2.8.2
    zfeed: ^0.2.4
  volar:
    "@volar/language-core": 2.4.27
    "@volar/typescript": 2.4.27
  vue:
    "@vitejs/plugin-vue": ^6.0.3
    "@vueuse/core": ^14.1.0
    "@vueuse/router": ^14.1.0
    pinia: ^3.0.4
    pinia-plugin-persistedstate: ^4.7.1
    vue: ^3.5.27
    vue-component-type-helpers: ^3.2.3
    vue-router: ^4.6.4
    vue-tsc: ^3.2.3

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - sharp
