shamefullyHoist: true

packages:
  - packages/*

patchedDependencies:
  mdast-util-to-hast: patches/mdast-util-to-hast.patch

catalogs:
  backend:
    "@iconify-json/fa6-solid": ^1.2.3
    "@kikiutils/nuxt-session": ^4.0.1
    "@nuxt/devtools": ^2.5.0
    "@nuxt/fonts": ^0.11.4
    "@nuxt/icon": ^1.13.0
    "@nuxt/image": ^1.10.0
    "@nuxtjs/seo": ^3.0.3
    "@pinia/nuxt": ^0.11.1
    "@vitejs/plugin-vue": ^5.2.4
    "@vue-email/render": ^0.0.9
    "@vueuse/nuxt": ^13.3.0
    "@zinkawaii/nuxt-shiki": ^0.9.0
    "@zinkawaii/tsconfig": ^0.0.2
    arktype: ^2.1.20
    chokidar: ^4.0.3
    cn-font-split: ^7.2.9
    consola: ^3.4.2
    cross-env: ^7.0.3
    crypto-es: ^2.1.0
    defu: ^6.1.4
    mongoose: ^8.16.0
    nuxt: ^3.17.5
    pathe: ^2.0.3
    propathy: ^0.2.1
    sass-embedded: ^1.89.2
    svgo: ^3.3.2
    undici: ^7.10.0
    unemail: ^0.2.0
    yaml: ^2.8.0
    zfeed: ^0.2.3
  build:
    tsdown: ^0.12.9
    vue-tsc: ^2.2.10
  frontend:
    "@vueuse/core": ^13.3.0
    "@vueuse/router": ^13.3.0
    animejs: ^4.0.2
    date-fns: ^4.1.0
    github-slugger: ^2.0.0
    hookable: ^5.5.3
    katex: ^0.16.22
    lunisolar: ^2.5.2
    pinia: ^3.0.3
    pinia-plugin-persistedstate: ^4.3.0
    plain-shiki: ^0.3.0
    shiki: ^3.6.0
    uqr: ^0.1.2
    vue: ^3.5.16
    vue-router: ^4.5.1
  lint:
    "@antfu/eslint-config": ^4.14.1
    "@zinkawaii/eslint-config": ^0.3.0
    "@zinkawaii/stylelint-config": ^0.3.2
    eslint: ^9.29.0
    stylelint: ^16.20.0
  markdown:
    "@mdzjs/config": ^0.0.1
    kerria: ^0.3.3
    mdast-util-frontmatter: ^2.0.1
    mdast-util-gfm-footnote: ^2.1.0
    mdast-util-gfm-strikethrough: ^2.0.0
    mdast-util-to-string: ^4.0.0
    micromark-extension-frontmatter: ^2.0.0
    micromark-extension-gfm-footnote: ^2.1.0
    micromark-extension-gfm-strikethrough: ^2.1.0
    micromark-util-symbol: ^2.0.1
    rehype-raw: ^7.0.0
    remark-math: ^6.0.0
    remark-mdc: ^3.6.0
    remark-parse: ^11.0.0
    remark-rehype: ^11.1.2
    unified: ^11.0.5
    unist-util-visit: ^5.0.0
  test:
    vitest: ^3.2.3
  types:
    "@types/wicg-file-system-access": ^2023.10.6

onlyBuiltDependencies:
  - "@parcel/watcher"
  - cn-font-split
  - esbuild
  - koffi
  - protobufjs
  - sharp
  - unrs-resolver
