minimumReleaseAge: 0
shamefullyHoist: true
shellEmulator: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - tinyclip@0.1.13

packages:
  - content
  - packages/*

define:
  - &bikariya ^0.0.8
  - &oxc ^0.136.0
  - &shiki ^4.2.0
  - &vls ^3.3.5
  - &volar 2.4.28
  - &vueuse ^14.3.0

overrides:
  "@dxup/nuxt": ^0.5.0
  "@nuxt/kit": npm:@nuxt/kit-nightly@5x
  esbuild: ^0.28.1
  h3: 2.0.1-rc.22
  nuxt: npm:nuxt-nightly@5x
  nuxtseo-layer-devtools: link:???
  oxc-minify: *oxc
  oxc-parser: *oxc
  oxc-transform: *oxc
  rolldown: ^1.1.1
  sharp: ^0.35.1
  vite: ^8.0.16

patchedDependencies:
  "@nuxt/icon": patches/@nuxt__icon.patch
  "@nuxt/image": patches/@nuxt__image.patch
  "@nuxtjs/robots": patches/@nuxtjs__robots.patch
  "@nuxtjs/sitemap": patches/@nuxtjs__sitemap.patch
  "@pinia/nuxt": patches/@pinia__nuxt.patch
  mdast-util-to-hast: patches/mdast-util-to-hast.patch
  nuxt-link-checker: patches/nuxt-link-checker.patch
  nuxt-og-image: patches/nuxt-og-image.patch
  nuxt-schema-org: patches/nuxt-schema-org.patch
  nuxt-seo-utils: patches/nuxt-seo-utils.patch
  nuxt-site-config: patches/nuxt-site-config.patch

catalogs:
  build:
    tsdown: ^0.22.3
    typescript: ^6.0.3
  content:
    kerria: ^0.5.0
    mdast-util-gfm-footnote: ^2.1.0
    mdast-util-gfm-strikethrough: ^2.0.0
    mdast-util-to-string: ^4.0.0
    micromark-extension-gfm-footnote: ^2.1.0
    micromark-extension-gfm-strikethrough: ^2.1.0
    micromark-util-symbol: ^2.0.1
    remark-breaks: ^4.0.0
    remark-frontmatter: ^5.0.0
    remark-math: ^6.0.0
    remark-mdc: ^3.11.0
    remark-parse: ^11.0.0
    remark-rehype: ^11.1.2
    unified: ^11.0.5
    unist-util-visit: ^5.1.0
  css:
    sass-embedded: ^1.100.0
  database:
    mongoose: ^9.7.1
  iconify:
    "@iconify-json/fa7-solid": ^1.2.4
  lint:
    "@zinkawaii/eslint-config": ^0.4.5
    "@zinkawaii/stylelint-config": ^0.4.1
    eslint: ^10.5.0
    stylelint: ^17.13.0
  nuxt:
    "@bikariya/image-viewer": *bikariya
    "@bikariya/modals": *bikariya
    "@bikariya/shiki": *bikariya
    "@nuxt/devtools": ^3.2.4
    "@nuxt/fonts": ^0.14.0
    "@nuxt/icon": ^2.2.3
    "@nuxt/image": ^2.0.0
    "@nuxtjs/seo": ^5.3.0
    "@pinia/nuxt": ^0.11.3
    "@vueuse/nuxt": *vueuse
    nuxt: ^4.4.8
  test:
    vitest: ^4.1.9
  types:
    "@types/node": ^25.9.3
    "@zinkawaii/tsconfig": ^0.1.0
  utils:
    "@aws-sdk/client-s3": ^3.1071.0
    "@aws-sdk/s3-request-presigner": ^3.1071.0
    "@clack/prompts": ^1.5.1
    "@shikijs/transformers": *shiki
    arktype: ^2.2.1
    bgmt: ^0.1.3
    chokidar: ^5.0.0
    consola: ^3.4.2
    crypto-es: ^3.1.3
    defu: ^6.1.7
    github-slugger: ^2.0.0
    hookable: ^6.1.1
    katex: ^0.17.0
    motion-v: ^2.3.0
    pathe: ^2.0.3
    plain-shiki: ^0.3.2
    propathy: ^0.2.1
    shiki: *shiki
    svgo: ^4.0.1
    temporal-polyfill: ^0.3.2
    tinyexec: ^1.2.4
    tinyglobby: ^0.2.17
    ufo: ^1.6.4
    unemail: ^0.4.1
    unrun: ^0.3.1
    uqr: ^0.1.3
    video-extensions: ^2.0.0
    yaml: ^2.9.0
    zfeed: ^0.2.4
  volar:
    "@volar/language-core": *volar
    "@volar/typescript": *volar
  vue:
    "@vitejs/plugin-vue": ^6.0.7
    "@vueuse/core": *vueuse
    "@vueuse/router": *vueuse
    pinia: ^3.0.4
    pinia-plugin-persistedstate: ^4.7.1
    vue: ^3.5.38
    vue-component-type-helpers: *vls
    vue-router: ^5.1.0
    vue-tsc: *vls

allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  sharp: true
  vue-demi: true
